name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select Terraform action"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        run: terraform plan
        env:
          TF_VAR_yc_token: ${{ secrets.YC_TOKEN }}
          TF_VAR_cloud_id: ${{ secrets.CLOUD_ID }}
          TF_VAR_folder_id: ${{ secrets.FOLDER_ID }}

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform apply -auto-approve
        env:
          TF_VAR_yc_token: ${{ secrets.YC_TOKEN }}
          TF_VAR_cloud_id: ${{ secrets.CLOUD_ID }}
          TF_VAR_folder_id: ${{ secrets.FOLDER_ID }}

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform destroy -auto-approve
        env:
          TF_VAR_yc_token: ${{ secrets.YC_TOKEN }}
          TF_VAR_cloud_id: ${{ secrets.CLOUD_ID }}
          TF_VAR_folder_id: ${{ secrets.FOLDER_ID }}