name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select Terraform action"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy
jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: terraform
    env:
      TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
      YC_CLOUD_ID: ${{ secrets.CLOUD_ID }}
      YC_FOLDER_ID: ${{ secrets.FOLDER_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      YC_TOKEN: ${{ secrets.YC_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init        
        run: terraform init

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        run: terraform plan

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform apply -auto-approve

      - name: Update HOST secret
        if: ${{ github.event.inputs.action == 'apply' }}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          IP=$(terraform output -raw vm_ip)
          echo "VM IP: $IP"
          gh secret set HOST --body "$IP" --repo ${{ github.repository }}
          echo "HOST secret updated"

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform destroy -auto-approve